import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import InitialLoader from "@/components/Loaders/InitialLoader";
import Visibility from "@/components/Sidebar/Visibilty";
import PageSwitchLoader from "@/components/Loaders/PageSwitchLoader";
import { ViewerProvider } from "@/components/Context/ViewerProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tomiwa Jinadu's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <InitialLoader />
        <ViewerProvider>
          <PageSwitchLoader />
          <Visibility> {children}</Visibility>
        </ViewerProvider>
      </body>
    </html>
  );
}
